assign0903/config/routes.rb
Rails.application.routes.draw do
  resources :holidays

  resources :schedules

  resources :supports

end

assign0903/app/models/holiday.rb
class Holiday < ActiveRecord::Base
	
end

assign0903/app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :Support
  validates :vacation, exclusion: {in: ['yes' , 'YES' ,'Yes'] , message: ":    This person is in the vacation , please eneter next avaliable support name"}
  validate :workingday

  def workingday
    require 'date'
    if  self.date.strftime("%a")== "sat" 
      errors.add(:date ,"      the day selected is the holiday , please schedule for next avaliable day")
    end

end

  
	
end

assign0903/app/models/support.rb
class Support < ActiveRecord::Base
	has_many :Schedules
end

assign0903/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

assign0903/app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  before_action :set_holiday, only: [:show, :edit, :update, :destroy]

  # GET /holidays
  # GET /holidays.json
  def index
    @holidays = Holiday.all
  end

  # GET /holidays/1
  # GET /holidays/1.json
  def show
  end

  # GET /holidays/new
  def new
    @holiday = Holiday.new
  end

  # GET /holidays/1/edit
  def edit
  end

  # POST /holidays
  # POST /holidays.json
  def create
    @holiday = Holiday.new(holiday_params)

    respond_to do |format|
      if @holiday.save
        format.html { redirect_to @holiday, notice: 'Holiday was successfully created.' }
        format.json { render :show, status: :created, location: @holiday }
      else
        format.html { render :new }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /holidays/1
  # PATCH/PUT /holidays/1.json
  def update
    respond_to do |format|
      if @holiday.update(holiday_params)
        format.html { redirect_to @holiday, notice: 'Holiday was successfully updated.' }
        format.json { render :show, status: :ok, location: @holiday }
      else
        format.html { render :edit }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /holidays/1
  # DELETE /holidays/1.json
  def destroy
    @holiday.destroy
    respond_to do |format|
      format.html { redirect_to holidays_url, notice: 'Holiday was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_holiday
      @holiday = Holiday.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def holiday_params
      params.require(:holiday).permit(:name, :Dateh)
    end
end

assign0903/app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
   

        if params.has_key?(:order) and params[:order] =="support_id"
     @schedules = Schedule.order("support_id")
   elsif params.has_key?(:today) and params[:today] =="support_id"
    require 'date'
    d = Date.today
     @schedules = Schedule.where("date =?" , d)

     else 
       @schedules = Schedule.all
     end 

  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:Support_id, :vacation, :Date)
    end
end

assign0903/app/controllers/supports_controller.rb
class SupportsController < ApplicationController
  before_action :set_support, only: [:show, :edit, :update, :destroy]

  # GET /supports
  # GET /supports.json
  def index
    @supports = Support.all
  end

  # GET /supports/1
  # GET /supports/1.json
  def show
  end

  # GET /supports/new
  def new
    @support = Support.new
  end

  # GET /supports/1/edit
  def edit
  end

  # POST /supports
  # POST /supports.json
  def create
    @support = Support.new(support_params)

    respond_to do |format|
      if @support.save
        format.html { redirect_to @support, notice: 'Support was successfully created.' }
        format.json { render :show, status: :created, location: @support }
      else
        format.html { render :new }
        format.json { render json: @support.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /supports/1
  # PATCH/PUT /supports/1.json
  def update
    respond_to do |format|
      if @support.update(support_params)
        format.html { redirect_to @support, notice: 'Support was successfully updated.' }
        format.json { render :show, status: :ok, location: @support }
      else
        format.html { render :edit }
        format.json { render json: @support.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supports/1
  # DELETE /supports/1.json
  def destroy
    @support.destroy
    respond_to do |format|
      format.html { redirect_to supports_url, notice: 'Support was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_support
      @support = Support.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def support_params
      params.require(:support).permit(:name, :phn, :email)
    end
end

assign0903/app/helpers/application_helper.rb
module ApplicationHelper
end

assign0903/app/helpers/holidays_helper.rb
module HolidaysHelper
end

assign0903/app/helpers/schedules_helper.rb
module SchedulesHelper
end

assign0903/app/helpers/supports_helper.rb
module SupportsHelper
end

assign0903/app/views/holidays/_form.html.erb
<%= form_for(@holiday) do |f| %>
  <% if @holiday.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@holiday.errors.count, "error") %> prohibited this holiday from being saved:</h2>

      <ul>
      <% @holiday.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :Dateh %><br>
    <%= f.date_select :Dateh %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

assign0903/app/views/holidays/edit.html.erb
<h1>Editing holiday</h1>

<%= render 'form' %>

<%= link_to 'Show', @holiday %> |
<%= link_to 'Back', holidays_path %>

assign0903/app/views/holidays/index.html.erb
<h1>Listing holidays</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Dateh</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @holidays.each do |holiday| %>
      <tr>
        <td><%= holiday.name %></td>
        <td><%= holiday.Dateh %></td>
        <td><%= link_to 'Show', holiday %></td>
        <td><%= link_to 'Edit', edit_holiday_path(holiday) %></td>
        <td><%= link_to 'Destroy', holiday, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Holiday', new_holiday_path %>

assign0903/app/views/holidays/new.html.erb
<h1>New holiday</h1>

<%= render 'form' %>

<%= link_to 'Back', holidays_path %>

assign0903/app/views/holidays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @holiday.name %>
</p>

<p>
  <strong>Dateh:</strong>
  <%= @holiday.Dateh %>
</p>

<%= link_to 'Edit', edit_holiday_path(@holiday) %> |
<%= link_to 'Back', holidays_path %>

assign0903/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assign0903</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

assign0903/app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Support_id %><br>
    <%= f.text_field :Support_id %>
  </div>
  <div class="field">
    <%= f.label :vacation %><br>
    <%= f.text_field :vacation %>
  </div>
  <div class="field">
    <%= f.label :Date %><br>
    <%= f.date_select :Date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

assign0903/app/views/schedules/edit.html.erb
<h1>Editing schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

assign0903/app/views/schedules/index.html.erb
<h1>Listing schedules</h1>
<br>
<a href="/schedules?order=support_id">order by supports</a> 
<br>
<a href="/schedules?today=support_id">today support hero</a> 
<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Support</th>
      <th>Date</th>
      <th>Vacation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.id %></td>
        <td><%= schedule.Support.name %></td>
        <td><%= schedule.Date %></td>
        <td><%= schedule.vacation %></td>
        <td><%= link_to 'Show', schedule %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
        <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schedule', new_schedule_path %>

assign0903/app/views/schedules/new.html.erb
<h1>New schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', schedules_path %>

assign0903/app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Support:</strong>
  <%= @schedule.Support %>
</p>

<p>
  <strong>Vacation:</strong>
  <%= @schedule.vacation %>
</p>

<p>
  <strong>Date:</strong>
  <%= @schedule.Date %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>

assign0903/app/views/supports/_form.html.erb
<%= form_for(@support) do |f| %>
  <% if @support.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@support.errors.count, "error") %> prohibited this support from being saved:</h2>

      <ul>
      <% @support.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phn %><br>
    <%= f.number_field :phn %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

assign0903/app/views/supports/edit.html.erb
<h1>Editing support</h1>

<%= render 'form' %>

<%= link_to 'Show', @support %> |
<%= link_to 'Back', supports_path %>

assign0903/app/views/supports/index.html.erb
<h1>Listing supports</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phn</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @supports.each do |support| %>
      <tr>
        <td><%= support.name %></td>
        <td><%= support.phn %></td>
        <td><%= support.email %></td>
        <td><%= link_to 'Show', support %></td>
        <td><%= link_to 'Edit', edit_support_path(support) %></td>
        <td><%= link_to 'Destroy', support, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Support', new_support_path %>

assign0903/app/views/supports/new.html.erb
<h1>New support</h1>

<%= render 'form' %>

<%= link_to 'Back', supports_path %>

assign0903/app/views/supports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @support.name %>
</p>

<p>
  <strong>Phn:</strong>
  <%= @support.phn %>
</p>

<p>
  <strong>Email:</strong>
  <%= @support.email %>
</p>

<%= link_to 'Edit', edit_support_path(@support) %> |
<%= link_to 'Back', supports_path %>